apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-autoscaler-plugins.fullname" . }}
  labels:
    {{- include "k8s-autoscaler-plugins.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-autoscaler-plugins.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "k8s-autoscaler-plugins.labels" . | nindent 8 }}
    spec:
      containers:
        - name: kopf
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            {{- with .Values.extraEnv }}
            {{- tpl (. | toYaml) $ | nindent 12 }}
            {{- end }}
          resources:
            {{- .Values.resources | toYaml | nindent 12 }}
          securityContext:
            {{- .Values.securityContext | toYaml | nindent 12 }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with include "k8s-autoscaler-plugins.serviceaccount.fullname" . }}
      serviceAccountName: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
