apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-autoscaler-plugins.clusterrole.fullname" . }}
rules:
  # Ref: https://docs.kopf.dev/en/stable/deployment/

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: watching and handling CRDs.
  - apiGroups: [jupyter.org]
    resources: [nodepoolallocationtargets]
    verbs: [get, list, watch, patch]

  # Application: list nodes
  - apiGroups: [""] # Core API group
    resources: [nodes]
    verbs: [list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-autoscaler-plugins.clusterrole.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-autoscaler-plugins.serviceaccount.fullname" . }}
    namespace: {{ .Release.Name }}
roleRef:
  kind: ClusterRole
  name: {{ include "k8s-autoscaler-plugins.clusterrole.fullname" . }}
  apiGroup: rbac.authorization.k8s.io