apiVersion: jupyter.org/v1
kind: NodepoolAllocationTarget
metadata:
  name: example-npat
spec:
  project: '<project_name>'
  cluster: '<cluster_name>'
  zone: '<zone_name>'
  nodepool: '<pool_name>'
  minimumNodeCount: 0
  