apiVersion: jupyter.org/v1
kind: NodepoolUtilizationThreshold
metadata:
  name: example-nput
spec:
  nodepoolLabelName: cloud.google.com/gke-nodepool
  nodepoolLabelValue: test-pool
  policy:
    type: memory
    minimumThreshold: 0.6
    maximumThreshold: 0.8