# This schema (a JSONSchema in YAML format) is used to generate
# values.schema.json to be packaged with the Helm chart.
#
# This schema is also planned to be used by our documentation system to build
# the configuration reference section based on the description fields. See
# docs/source/conf.py for that logic in the future!
#
# We look to document everything we have default values for in values.yaml, but
# we don't look to enforce the perfect validation logic within this file.
#
# ref: https://helm.sh/docs/topics/charts/#schema-files
# ref: https://json-schema.org/learn/getting-started-step-by-step.html
#
$schema: http://json-schema.org/draft-07/schema#
type: object
additionalProperties: false
required:
  # General configuration
- global
- extraEnv
- image
- rbac
- service
- serviceAccount
properties:
  # Flag to conditionally install the chart
  # ---------------------------------------------------------------------------
  #
  enabled:
    type: boolean
    description: |
      Configuration flag for charts depending on k8s-autoscaler-plugins to toggle installing it.

  # General configuration
  # ---------------------------------------------------------------------------
  #
  nameOverride:
    type: [string, 'null']
  fullnameOverride:
    type: [string, 'null']
  global:
    type: object
    additionalProperties: true

  # Deployment resource
  # ---------------------------------------------------------------------------
  #
  replicas:
    type: integer
  extraEnv:
    type: array
  image:
    type: object
    additionalProperties: false
    required: [repository, tag]
    properties:
      repository:
        type: string
      tag:
        type: string
      pullPolicy:
        enum: [null, '', IfNotPresent, Always, Never]
      pullSecrets:
        type: array
  resources:
    type: object
    additionalProperties: true
  securityContext:
    type: object
    additionalProperties: true
  podSecurityContext:
    type: object
    additionalProperties: true
  podAnnotations: &labels-and-annotations
    type: object
    additionalProperties: false
    patternProperties:
      .*:
        type: string
  nodeSelector:
    type: object
    additionalProperties: true
  affinity:
    type: object
    additionalProperties: true
  tolerations:
    type: array

  # Service resource
  # ---------------------------------------------------------------------------
  #
  service:
    type: object
    additionalProperties: false
    required: [type, port]
    properties:
      type:
        type: string
      port:
        type: integer
      nodePort:
        type: integer
      annotations: *labels-and-annotations

  # ServiceAccount resource
  # ---------------------------------------------------------------------------
  #
  serviceAccount:
    type: object
    additionalProperties: false
    required: [create, name]
    properties:
      create:
        type: boolean
      name:
        type: string
      annotations: *labels-and-annotations

  # RBAC resource
  # ---------------------------------------------------------------------------
  #
  rbac:
    type: object
    additionalProperties: false
    required: [create, name]
    properties:
      create:
        type: boolean
      name:
        type: string
      annotations: *labels-and-annotations